### ISSUE TITLE
Sample player processor discussion

### ISSUE THREAD

**Issue by boourns** [timchurches/Mutated-Mutables#3]
As mentioned in #2 I'm working on a sample player.

Current plan for controls are:
- pick sample
- tune (relatively wide range for sonic exploration)
- decay (will trim samples that are tuned down, and samples turned up could loop until decay finishes)
- distortion, or sample rate reduction.. some sort of effect.

For samples I was thinking it'd be a good opportunity to widen the sonic palette of the module, adding perhaps other drum sounds that are harder to realistically synthesize like claps and some other percussion samples.

It's really cool that someone recorded hihat samples just for this module but on first listen I'm not sure how much breadth they add to the DMC palette after being downsampled.

Right now I have it working at 24k sample rate, which will provide ~2-3 seconds sample time.  Runtime decompression would be possible but I think it might exhaust my interest in this project before I got it working :)

**Comment by timchurches** [comment]
I think they were downsampled because they were going to be used as
replacements for the numbers station samples. I don't entirely recall what
was planned. If better samples will fit, then might as well add them.
